{% set name = "regols" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kitagry/regols/archive/v{{ version }}.tar.gz
  sha256: 7d99e08cf527bb8d27b287b39f9c3ee170486c78a6ad6c92e8f69663c91c8c18

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - regols --help

about:
  home: https://github.com/kitagry/regols
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: AOPA Rego language server
  dev_url: https://github.com/kitagry/regols

extra:
  recipe-maintainers:
    - danielnachun
